### ISSUE TITLE
What is the correct way to add bootstrap in this project?

### ISSUE THREAD

**Issue by YisusW** [emicarito/calendar-app#1]
I was trying to do this `import 'bootstrap/dist/css/bootstrap.css';` in **index.tsx** and `import '../node_modules/bootstrap/dist/css/bootstrap.min.css';` and webpack print `@ multi react-hot-loader/patch ./src/index.tsx` in really red color.

**Comment by emicarito** [comment]
You need to add a new rule on your module in webpack.config.js
```
{
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
```
